### ISSUE TITLE
is this still being work on?

### ISSUE THREAD

**Issue by M1chaelTran** [nharris85/node_acl_dynamodb#1]
hey @nharris85 

thank you for putting this together.
I noticed on your last commit stating the test are still failing.

Do you need help to resolve those issues and if you are still working on this?

**Comment by nikordaris** [comment]
hey @M1chaelTran 

This has definitely fallen off my radar. My project moved on to a different DB before I could finish this. I have other projects that I expect will use DynamoDB but haven't had the time to circle back around to this. 

I welcome any help you want to offer. I think it was really close to being done.

**Comment by matthoward** [comment]
@nikordaris @M1chaelTran I'm on a project now looking into which backend we're going to use with node_acl. I *think* we're going to try to use this dynamodb backend, so I've taken a quick stab at getting the tests to work. I have a fork where I have the tests all passing, but I've made some changes I thought I should run by you if you want to keep this project going:

1. I just removed the encodeURIComponent and decodeURIComponent as it was causing the tests for user 'test@test.com' to fail. I don't know if these need to be re-instated in order to resolve some other issue I'm not aware of. I haven't yet dug into *why* those tests fail with this encoding logic in place. I can do that if you think it is needed. 
2. Not needed to fix the tests, but when useSingle = false I am currently still forcing all the acl_allows* records to use a single allows table, rather than 1 per resource. This is because on my project we will have probably hundreds of resources defined and will hit the dynamo limit (we could request a limit increase but I'd like to keep the tables a little cleaner). I've seen other node_acl backends do something similar. I'm considering making this behavior another option... but haven't thought through how to make it clear.   

For the other tests basically all I had to do to get them to pass were some minor tweaks:

1. force all keys/values to a String, to fix the tests where userId was numeric 
2. make "remove()" use ExpressionAttributeNames, otherwise executing a remove on a "get" permission caused a problem due to "get" being a reserved word. 
3. change the "prefix" in the default/single tests to use a different prefix, since otherwise the table acl_resources needs a different structure (range key on bucketname) for the "single" vs default, and so queries were failing.  
4. strip out invalid chars in the table names... before I changed the "allows_*" to all be in a single table this was needed because resources like "/path/file/file2.txt" are invalid table names. 
5. add "_bucketname" to the lodash.without() list... otherwise the isSingle=true tests fail for having this extra data in the output

You can see the diff at https://github.com/nikordaris/node_acl_dynamodb/compare/master...matthoward:fix-tests?expand=1 

I don't think it's ready to merge yet - want to clean up some things first (and I used some es6 syntax I might need to redo unless you mind bumping the node engine compatibility). But if you want me to merge the fixes let me know your thoughts on the above... especially the URI encoding and the single allows_ table logic.

**Comment by nikordaris** [comment]
@matthoward great work! Please do submit a pull request when you are ready. Bumping the node engine up is a welcomed improvement.
